//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refeicoes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\GONÇALO\\DOCUMENTS\\ALM" +
            "OCOS\\REFEICOES\\REFEICOES\\BIN\\DEBUG\\REGISTOSSAIDAS.MDF;Integrated Security=True")]
        public string refeicoesConnectionString {
            get {
                return ((string)(this["refeicoesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\GONÇALO\\DOCUMENTS\\ALM" +
            "OCOS\\REFEICOES\\REFEICOES\\BIN\\DEBUG\\REGISTOSSAIDAS.MDF;Integrated Security=True")]
        public string D__IPE_PAPS_AMARO_WINDOWSAPPLICATION1_BIN_DEBUG_REGISTOSSAIDAS_MDFConnectionString {
            get {
                return ((string)(this["D__IPE_PAPS_AMARO_WINDOWSAPPLICATION1_BIN_DEBUG_REGISTOSSAIDAS_MDFConnectionStrin" +
                    "g"]));
            }
        }
    }
}
